version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "composer"
    versioning-strategy: "increase-if-necessary"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    rebase-strategy: "disabled"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "node"
    versioning-strategy: "increase-if-necessary"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    groups:
      # this should group all minor and patch-level updates together
      main-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    rebase-strategy: "disabled"
